fpm-deployment: update `VERSION` field in fpm.toml with actual version
fortran-lang/stdlib pull request #702
Opened 2023-03-15 11:07 UTC by perazz

See #701, this update in the fpm deployment script updates the `VERSION` placeholder in fpm.toml so an actual version is printed. 

I don't know how to test the deployment on my fork.

2023-03-17 20:14 UTC, jvdp1 approved these changes
LGTM. Thanks @perazz for this PR.

2023-03-18 17:19 UTC, arteevraina approved these changes

2023-03-18 17:22 UTC, arteevraina commented
> I don't know how to test the deployment on my fork.

You can try running this script locally and try to generate the fpm compatible ``stdlib`` ? and look if the changes are reflected in ``fpm.toml``.

2023-03-18 17:31 UTC, awvwgk requested changes
Why is this change necessary? We already deploy the `VERSION` file correctly for the stdlib-fpm branch.

2023-03-18 21:13 UTC, perazz commented
Currently, fpm.toml in the deployed branch reports `version = "VERSION"`, is this a feature? This proposed change updates that field with the actual version, i.e., `version = "0.2.1"`

2023-03-18 21:41 UTC, awvwgk commented
> Currently, fpm.toml in the deployed branch reports `version = "VERSION"`; this proposed change updates that field with the actual version, i.e., `version = "0.2.1"`

Maybe, I misunderstand something here, but this is exactly what is expected. The version is already deployed correctly in [`VERSION`](https://github.com/fortran-lang/stdlib/blob/stdlib-fpm/VERSION) on the `stdlib-fpm` branch. It will be read dynamically by the fpm binary. So why do we need to change the manifest at all?

If I recall correctly, I actually implemented this feature of reading the version from a file in fpm for stdlib to have a single place to specify the version for both build systems (fpm and CMake).

2023-03-19 08:23 UTC, perazz commented
Oh [I see](https://fpm.fortran-lang.org/en/spec/manifest.html?highlight=versio#project-version), version can be an external file. If we were going to support stdlib as a metapackage, I thought it was intuitive for the fpm-specific deployment to have a manifest file that contains all relevant pieces of information.

2023-03-19 10:59 UTC, awvwgk commented
That was unfortunately never true, especially due to the default names for the source directories as well as the automatic discovery of executables, the TOML manifest alone is usually incomplete. Running fpm will generate an internal representation which is complete, the two options are to have fpm dump the internal model or reimplements the whole logic supported by fpm.

2023-06-15 19:05 UTC, jvdp1 commented
@perazz @awvwgk Is this PR still needed? Or could it be closed without merging it?

2023-06-15 19:22 UTC, perazz commented
Please close without merging @jvdp1, thank you.

2023-06-15 19:30 UTC, jvdp1 commented
Ok. Thank you.

2023-06-15 19:30 UTC, closed without merging